services:
  - type: web
    name: livro-api
    # A linha abaixo foi alterada para 'docker'
    runtime: docker
    region: oregon
    plan: free
    # Removemos o bloco envVars, buildCommand e startCommand
    # O Dockerfile agora cuida de tudo isso.
    healthCheckPath: /q/health/live
    # Adicione o caminho do Dockerfile (opcional, mas bom para clareza)
    dockerfilePath: ./Dockerfile